#cloud-config

hostname: ${node_name}
fqdn: ${node_name}.${internal_domain}

package_update: true
package_upgrade: false

packages:
  - curl

write_files:
  - path: /etc/salt/minion.d/wazuh.conf
    content: |
      master: ${master_ip}
      id: ${node_name}.${internal_domain}

  - path: /etc/hosts
    content: |
      127.0.0.1 localhost
      %{ for name, node in nodes ~}
      ${node.fixed_ip} ${name}.${internal_domain} ${name}
      %{ endfor ~}

runcmd:
  - curl -fsSL -o /tmp/bootstrap-salt.sh https://bootstrap.saltproject.io
  - sh /tmp/bootstrap-salt.sh stable
  - systemctl enable salt-minion
  - systemctl restart salt-minion
