#cloud-config

hostname: salt-master

package_update: true
package_upgrade: false

packages:
  - curl
  - git

write_files:
  - path: /etc/salt/master.d/wazuh.conf
    content: |
      autosign_grains_dir: /etc/salt/autosign_grains

      file_roots:
        base:
          - /srv/salt

      pillar_roots:
        base:
          - /srv/pillar

  - path: /etc/salt/autosign_grains/fqdn
    content: |
      *.${internal_domain}

  - path: /etc/hosts
    content: |
      127.0.0.1 localhost
      %{ for name, ip in node_ips ~}
      ${ip} ${name}.${internal_domain} ${name}
      %{ endfor ~}

runcmd:
  - curl -fsSL -o /tmp/bootstrap-salt.sh https://bootstrap.saltproject.io
  - sh /tmp/bootstrap-salt.sh -M stable
  - git clone ${repository} /tmp/wazuh-repo
  - cp -r /tmp/wazuh-repo/salt/srv/* /srv/salt/
  - cp -r /tmp/wazuh-repo/salt/pillar/* /srv/pillar/
  - rm -rf /tmp/wazuh-repo
  - systemctl enable salt-master salt-minion
  - systemctl restart salt-master salt-minion
