#cloud-config

hostname: ${node_name}
fqdn: ${node_name}.${internal_domain}

package_update: true
package_upgrade: false

packages:
  - curl

write_files:
  - path: /etc/hosts
    content: |
      127.0.0.1 localhost
%{ for name, ip in node_ips ~}
      ${ip} ${name}.${internal_domain} ${name}
%{ endfor ~}
  - path: /etc/salt/pki/minion/minion.pem
    content: |
      ${minion_priv_key}
    permissions: '0400'
  - path: /etc/salt/pki/minion/minion.pub
    content: |
      ${minion_pub_key}
    permissions: '0644'
  - path: /etc/salt/minion.d/wazuh.conf
    content: |
      master: ${master_ip}
      id: ${node_name}.${internal_domain}

runcmd:
  - mkdir -p /etc/salt/minion.d /etc/salt/pki/minion
  - systemctl mask salt-minion
  - curl -fsSL -o /tmp/bootstrap-salt.sh https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh
  - sh /tmp/bootstrap-salt.sh stable
  - systemctl unmask salt-minion
  - systemctl enable salt-minion
  - systemctl restart salt-minion
