name: Deploy Salt states

on:
  push:
    branches:
      - master
    paths:
      - "salt/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Salt states and run highstate
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SALT_MASTER_IP }}
          username: ubuntu
          key: ${{ secrets.SALT_MASTER_SSH_KEY }}
          command_timeout: 30m
          script: |
            if [ -d /tmp/wazuh-repo ]; then
              cd /tmp/wazuh-repo && git pull
            else
              git clone ${{ secrets.REPOSITORY }} /tmp/wazuh-repo
            fi
            sudo cp -r /tmp/wazuh-repo/salt/srv/* /srv/salt/
            sudo cp -r /tmp/wazuh-repo/salt/pillar/* /srv/pillar/
            sudo salt-run state.orchestrate wazuh.orch.generate_certs
            sudo salt '*' state.highstate
